### ISSUE TITLE
Two documentation errors

### ISSUE THREAD

**Issue by xuchunyang** [wbthomason/msgpack-rpc-racket#1]
https://docs.racket-lang.org/msgpack-rpc/index.html?q=match#%28part._sync-call%29

    (let-values ([(err result) (rpc-call client "plusone" 4)]))

`rpc-call` returns a list `(err result)`, thus `let-values` doesn't work.

---

https://docs.racket-lang.org/msgpack-rpc/index.html?q=match#%28part._async-call%29

    (define chan ((rpc-call client "plusone" 4 #:sync? #f)))

it should be

    (define chan (rpc-call client "plusone" 4 #:sync? #f))

**Comment by wbthomason** [comment]
Hi, @xuchunyang! Thanks for the bug reports.

> `rpc-call` returns a list `(err result)`, thus `let-values` doesn't work.

My bad! I changed the API (originally, the callback handler made by `make-response-handler` put `(values err result)` into the callback channel instead of `(list err result)`)  and forgot to make the docs match. I'm leaving the API as it is and changing the documentation example to
```racket
(match-let ([(list err result) (rpc-call client "plusone" 4)]) ...)
```
which I believe should be correct. I'll make the corresponding update for the `async-call` example, which shares the same bug.

> ```racket 
> (define chan ((rpc-call client "plusone" 4 #:sync? #f)))
>```
>...should be...

Ah, thanks for catching this typo. I'm fixing it as you suggest.
